blank_issues_enabled: true
contact_links:
  - name: General question or discussion
    url: https://github.com/
    about: Use GitHub Discussions or open a blank issue if your request is not a bug report or feature request.
